name: API Tests

on:
    workflow_dispatch:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout project
        uses: actions/checkout@v4

      # 2. Устанавливаем JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Даем права на выполнение gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Запускаем API тесты
      - name: Run API tests
        run: ./gradlew clean testApi

      # 5. Копируем историю предыдущих Allure отчетов
      - name: Copy history
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      # 6. Генерируем новый Allure отчет
      - name: Build Allure Report
        if: always()
        uses: simple-elf/allure-report-action@v1.10
        with:
          allure_results: build/allure-results
          allure_history: allure-history
          keep_reports: 20

      # 7. Публикуем отчет на GitHub Pages
      - name: Deploy Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        with:
          personal_token: ${{ secrets.TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          force_orphan: true

